#!/bin/bash

echo "======================================================================"
echo "         FRAUDSHIELD AI - STREAMLIT APPLICATION STARTUP"
echo "======================================================================"
echo ""
echo "Installing Streamlit dependencies..."
pip install streamlit plotly --quiet
echo ""
echo "Starting Streamlit Application..."
echo ""
echo "======================================================================"
echo "         APPLICATION STARTING"
echo "======================================================================"
echo ""
echo "[INFO] Streamlit application is launching..."
echo "[INFO] Web interface will open automatically"
echo "[INFO] Application URL: http://localhost:8501"
echo ""
echo "[INSTRUCTIONS]:"
echo "  1. Access the web interface at http://localhost:8501"
echo "  2. Select from the navigation menu:"
echo "     - Fraud Detection: Detect fraud in single messages"
echo "     - Batch Processing: Analyze multiple messages"
echo "     - Statistics: View model info and performance metrics"
echo "     - About: Learn more about FraudShield AI"
echo "  3. Press Ctrl+C to stop the application"
echo ""
echo "======================================================================"
cd "$(dirname "$0")"
streamlit run streamlit_app.py --logger.level=error
